### ISSUE TITLE
docker.new-telerising-api inlusive with openvpn-client possible ?

### ISSUE THREAD

**Issue by Jano69** [DeBaschdi/docker.new-telerising-api#4]
Hello,
is it possible to push this container with an Openvpn client? this way you can bypass geoblocking individually.
Store data in / etc / openvpn and off you go ..... that would be really heavenly!

**Comment by srudin** [comment]
This is an old post and I'm NOT the owner of the repo, but in order to maybe contribute somehow and take away the feeling that you are all alone here I will try to answer:

I think there is no need for a vpn client. Telerising is eliminating the geoblocking by itself which is actually one of its great features. I am using it from outside the providers home country and things work great without any vpn.

**Comment by DeBaschdi** [comment]
Ich bin Entwickler des Dockers, bei API Fragen bitte den Supportthread auf Kodinerds nutzen, oder beim Entwickler nachfragen.
Danke und immer freundlich bleiben.
